name: Deploy to GitHub Pages

# run on every push to main
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. check out your repo
      - name: Checkout
        uses: actions/checkout@v3

      # 2. set up Node (v18 is fine for CRA)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. build your app
      - name: Build
        run: npm run build

      # 5. deploy the contents of build/ to gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
